### ISSUE TITLE
I can't save pmc or ahk files. 

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [samfisherirl/Pulovers-Macro-Creator-for-AHKv2#3]
I can't save pmc or ahk files. I think the save dialog has a bug and it's **for a "load" dialog**.
Please double-check the implementation of all the parts that **save any files.**

**Comment by samfisherirl** [comment]
> I can't save pmc or ahk files. I think the save dialog has a bug and it's **for a "load" dialog**. Please double-check the implementation of all the parts that **save any files.**

itll take some time for me to trace this. I see that doesnt work.

**Comment by Tsukasa-YAMATO** [comment]
I use the Japanese version of Windows 10. But I can read English. As shown in the attached image, I was using PMC with the English UI. When I clicked Save As icon, the save dialog called up the Japanese file save screen. It means "開く(O) Open file" and "キャンセル(Cancel)" dialog buttons. The characters at the end of the arrow in the image are written in Japanese Kanji, Hiragana and Katakana.

This bug is probably a coding mistake when AHK calls the Windows file opening and saving commands.

Considering this, it seems that the cause of the bug is that the Windows file save procedure should be called in the main routine, but the Windows "load file" procedure is mistakenly specified in the main routine. It is possible that somewhere in the code you added or changed has mistakenly specified the Windows "load file" procedure. In other words, when using the Windows mechanism, it is highly likely that the file load procedure command is mistakenly specified instead of the Windows file save procedure command.

I have made a similar mistake myself in a programming language other than AHK. My problem at the time was a mistake in the description of the FileSave and FileLoad commands. The cause of the mistake was that I copied and pasted the file operation-related source code from FileLoad to implement file saving. I felt that this was the same as my experience at that time, so I decided to attach an image and write the details here.
![PMC-SaveAs-bug](https://github.com/samfisherirl/Pulovers-Macro-Creator-for-AHKv2/assets/65609416/f97fd7b7-2bf3-4c09-ae46-b41a95f3e920)

**Comment by samfisherirl** [comment]
> I use the Japanese version of Windows 10. But I can read English. As shown in the attached image, I was using PMC with the English UI. When I clicked Save As icon, the save dialog called up the Japanese file save screen. It means "開く(O) Open file" and "キャンセル(Cancel)" dialog buttons. The characters at the end of the arrow in the image are written in Japanese Kanji, Hiragana and Katakana.
> 
> This bug is probably a coding mistake when AHK calls the Windows file opening and saving commands.
> 
> Considering this, it seems that the cause of the bug is that the Windows file save procedure should be called in the main routine, but the Windows "load file" procedure is mistakenly specified in the main routine. It is possible that somewhere in the code you added or changed has mistakenly specified the Windows "load file" procedure. In other words, when using the Windows mechanism, it is highly likely that the file load procedure command is mistakenly specified instead of the Windows file save procedure command.
> 
> I have made a similar mistake myself in a programming language other than AHK. My problem at the time was a mistake in the description of the FileSave and FileLoad commands. The cause of the mistake was that I copied and pasted the file operation-related source code from FileLoad to implement file saving. I felt that this was the same as my experience at that time, so I decided to attach an image and write the details here. ![PMC-SaveAs-bug](https://private-user-images.githubusercontent.com/65609416/338995328-f97fd7b7-2bf3-4c09-ae46-b41a95f3e920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMjk2MjEsIm5iZiI6MTcxODIyOTMyMSwicGF0aCI6Ii82NTYwOTQxNi8zMzg5OTUzMjgtZjk3ZmQ3YjctMmJmMy00YzA5LWFlNDYtYjQxYTk1ZjNlOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIxNTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNmUxMGU4YzQwODZhZWY4NjljOTU2OGNjYzk3MDM1ZGY1NTI3MWFhNGYyNWNiNDQyMDkxN2M2NDMwNTc5MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKPvGKf5-K7w8gYriUYUTlDd2F9pMU3jxjUYyjkUAaQ)

fixed

修理済み
